### ISSUE TITLE
Import Build does nothing

### ISSUE THREAD

**Issue by zbee** [aeon0/d4lf#235]
Initially I tried this with `firefox`, then tried `chrome` and `edge`, and for me none of them do anything.

I got `firefox` to open the window once, but it didn't do anything, and I can't get the window to open again.

No errors appear in the log, no window or tab opens whether the browser is open before pressing the hotkey or closed, just nothing; and on top of that, it locks up d4lf until I close it altogether, not even <kbd>ctrl</kbd>+<kbd>C</kbd> works quite right to end the process.

---

<details>

<summary>Here are some rather sparse Logs, despite <code>log_lvl=debug</code></summary>

```
[5.1.1 2024-05-22 05:49:57,426] INFO Using WinAPI to search for window: diablo iv.exe
[5.1.1 2024-05-22 05:49:57,431] INFO Found Window Res: 3440x1440
[5.1.1 2024-05-22 05:49:57,659] INFO Adapt your custom configs in: C:\Users\Pwnjo.d4lf
[5.1.1 2024-05-22 05:49:57,664] INFO Loading profile sigils: Sigils
[5.1.1 2024-05-22 05:49:57,674] INFO Loading profile sminion-level: Affixes Uniques
[5.1.1 2024-05-22 05:50:01,673] INFO Paste maxroll.gg build guide or planner build here ie https://maxroll.gg/d4/build-guides/minion-necromancer-guide
```

</details>

<details>

<summary>My <code>params.ini</code></summary>

```
[general]
; Which filter profiles should be run. All .yaml files with "Aspects" and "Affixes" sections will be used from
; config/profiles/*.yaml and C:/Users/USERNAME/.d4lf/profiles/*.yaml
profiles=sigils,sminion-level
; from C:\Users\Pwnjo\.d4lf

; Whether to keep aspects. Can be all, upgrade, none
keep_aspects=upgrade
; upgrade includes undiscovered aspects

; How to handle rares. Can be filter, ignore, junk
handle_rares=filter
; it's so cheap now

; Whether to run vision mode on startup or not
run_vision_mode_on_startup=False
; too slow

; Which tabs to check. Note: All 6 Tabs must be unlocked!
check_chest_tabs=1

; Transparancy of the overlay when not hovering it (has a 3 second dealy after hovering)
; The "shown" transparncy is 0.94
hidden_transparency=0.35

; Which browser to use to get builds, Chrome, Edge, or Firefox are currently supported
; Note: edge and firefox are not well tested, use chrome to be on the safe side
browser=firefox

[char]
; Hotkey to open inventory
inventory=g

[advanced_options]
; Run the filter
run_filter=f4
; Exit
exit_key=f6
; Open browser to import a build
import_build=f7

; Which scripts to run
scripts=vision_mode
; Run scripts, eg vision or potting
run_scripts=f1

; Debug level
log_lvl=debug
; Process to look for
process_name=Diablo IV.exe

```

</details>

**Comment by zbee** [comment]
I have misunderstood - the URL needs pasted into the program which then opens that page (could use some more verbosity, in my opinion). I can now get it to provide errors:

<details>
<summary>chrome (and edge)</summary>

```
[5.1.1 2024-05-22 06:31:02,659] INFO       Paste maxroll.gg build guide or planner build here ie https://maxroll.gg/d4/build-guides/minion-necromancer-guide
https://maxroll.gg/d4/build-guides/shadow-minion-necromancer-guide

DevTools listening on ws://127.0.0.1:59419/devtools/browser/ed61bd53-027c-4512-b5eb-385e8ec3fb6e
[32320:21952:0522/063113.225:ERROR:device_event_log_impl.cc(195)] [06:31:13.225] USB: usb_service_win.cc:105 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
Created TensorFlow Lite XNNPACK delegate for CPU.
Exception in thread Thread-2 (process):
Traceback (most recent call last):
  File "threading.py", line 1073, in _bootstrap_inner
  File "threading.py", line 1010, in run
  File "keyboard\_generic.py", line 58, in process
  File "keyboard\__init__.py", line 218, in pre_process_event
  File "keyboard\__init__.py", line 649, in <lambda>
  File "main.py", line 43, in <lambda>
  File "utils\build_importer.py", line 57, in import_build
  File "selenium\webdriver\support\wait.py", line 105, in until
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
        GetHandleVerifier [0x00007FF714B91522+60802]
        (No symbol) [0x00007FF714B0AC22]
        (No symbol) [0x00007FF7149C7CE4]
        (No symbol) [0x00007FF714A16D4D]
        (No symbol) [0x00007FF714A16E1C]
        (No symbol) [0x00007FF714A5CE37]
        (No symbol) [0x00007FF714A3ABBF]
        (No symbol) [0x00007FF714A5A224]
        (No symbol) [0x00007FF714A3A923]
        (No symbol) [0x00007FF714A08FEC]
        (No symbol) [0x00007FF714A09C21]
        GetHandleVerifier [0x00007FF714E941BD+3217949]
        GetHandleVerifier [0x00007FF714ED6157+3488183]
        GetHandleVerifier [0x00007FF714ECF0DF+3459391]
        GetHandleVerifier [0x00007FF714C4B8E6+823622]
        (No symbol) [0x00007FF714B15FBF]
        (No symbol) [0x00007FF714B10EE4]
        (No symbol) [0x00007FF714B11072]
        (No symbol) [0x00007FF714B018C4]
        BaseThreadInitThunk [0x00007FFC7C14257D+29]
        RtlUserThreadStart [0x00007FFC7DCCAA48+40]

```

</details>

<details>
<summary>firefox</summary>

```
[5.1.1 2024-05-22 06:33:52,795] INFO       Paste maxroll.gg build guide or planner build here ie https://maxroll.gg/d4/build-guides/minion-necromancer-guide
https://maxroll.gg/d4/build-guides/shadow-minion-necromancer-guide
Exception in thread Thread-2 (process):
Traceback (most recent call last):
  File "threading.py", line 1073, in _bootstrap_inner
  File "threading.py", line 1010, in run
  File "keyboard\_generic.py", line 58, in process
  File "keyboard\__init__.py", line 218, in pre_process_event
  File "keyboard\__init__.py", line 649, in <lambda>
  File "main.py", line 43, in <lambda>
  File "utils\build_importer.py", line 57, in import_build
  File "selenium\webdriver\support\wait.py", line 105, in until
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
```

</details>

**Comment by crafty35a** [comment]
I'm getting the same error, Chrome is my default browser

**Comment by hatchcanon** [comment]
I'm getting the same error, Firefox is my default browser but also fails with Chrome

**Comment by chrisoro** [comment]
Will take a look guys

**Comment by aeon0** [comment]
> I have misunderstood - the URL needs pasted into the program which then opens that page (could use some more verbosity, in my opinion). I can now get it to provide errors: Firefox is the only one that opens, but does nothing but throw an error, Chrome and Edge don't even open only throwing errors.
> 
> chrome (and edge)
> ```
> [5.1.1 2024-05-22 06:31:02,659] INFO       Paste maxroll.gg build guide or planner build here ie https://maxroll.gg/d4/build-guides/minion-necromancer-guide
> https://maxroll.gg/d4/build-guides/shadow-minion-necromancer-guide
> 
> DevTools listening on ws://127.0.0.1:59419/devtools/browser/ed61bd53-027c-4512-b5eb-385e8ec3fb6e
> [32320:21952:0522/063113.225:ERROR:device_event_log_impl.cc(195)] [06:31:13.225] USB: usb_service_win.cc:105 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
> Created TensorFlow Lite XNNPACK delegate for CPU.
> Exception in thread Thread-2 (process):
> Traceback (most recent call last):
>   File "threading.py", line 1073, in _bootstrap_inner
>   File "threading.py", line 1010, in run
>   File "keyboard\_generic.py", line 58, in process
>   File "keyboard\__init__.py", line 218, in pre_process_event
>   File "keyboard\__init__.py", line 649, in <lambda>
>   File "main.py", line 43, in <lambda>
>   File "utils\build_importer.py", line 57, in import_build
>   File "selenium\webdriver\support\wait.py", line 105, in until
> selenium.common.exceptions.TimeoutException: Message:
> Stacktrace:
>         GetHandleVerifier [0x00007FF714B91522+60802]
>         (No symbol) [0x00007FF714B0AC22]
>         (No symbol) [0x00007FF7149C7CE4]
>         (No symbol) [0x00007FF714A16D4D]
>         (No symbol) [0x00007FF714A16E1C]
>         (No symbol) [0x00007FF714A5CE37]
>         (No symbol) [0x00007FF714A3ABBF]
>         (No symbol) [0x00007FF714A5A224]
>         (No symbol) [0x00007FF714A3A923]
>         (No symbol) [0x00007FF714A08FEC]
>         (No symbol) [0x00007FF714A09C21]
>         GetHandleVerifier [0x00007FF714E941BD+3217949]
>         GetHandleVerifier [0x00007FF714ED6157+3488183]
>         GetHandleVerifier [0x00007FF714ECF0DF+3459391]
>         GetHandleVerifier [0x00007FF714C4B8E6+823622]
>         (No symbol) [0x00007FF714B15FBF]
>         (No symbol) [0x00007FF714B10EE4]
>         (No symbol) [0x00007FF714B11072]
>         (No symbol) [0x00007FF714B018C4]
>         BaseThreadInitThunk [0x00007FFC7C14257D+29]
>         RtlUserThreadStart [0x00007FFC7DCCAA48+40]
> ```
> 
> firefox

You are pasting the build guide. That wont work. You have to paste a build, not a guide. E.g. https://maxroll.gg/d4/planner/dqih026y#3

**Comment by zbee** [comment]
Suggest also updating the readme then, as well as adding verbose instruction as earlier suggested: https://github.com/aeon0/d4lf/blob/9afa74daabc3ddf5533f031606f41ed163e298a9/README.md?plain=1#L315
And the log message:
> [5.1.1 2024-05-22 06:31:02,659] INFO       Paste maxroll.gg **_build guide_** or planner build here ie https://maxroll.gg/d4/build-guides/minion-necromancer-guide

---

When I paste one of the planers from that guide I now get this: (same error with `#6` at the end)

```
[5.1.1 2024-05-22 11:09:05,873] INFO       Paste maxroll.gg build guide or planner build here ie https://maxroll.gg/d4/build-guides/minion-necromancer-guide
https://maxroll.gg/d4/planner/dqih026y
Exception in thread Thread-2 (process):
Traceback (most recent call last):
  File "threading.py", line 1073, in _bootstrap_inner
  File "threading.py", line 1010, in run
  File "keyboard\_generic.py", line 58, in process
  File "keyboard\__init__.py", line 218, in pre_process_event
  File "keyboard\__init__.py", line 649, in <lambda>
  File "main.py", line 43, in <lambda>
  File "utils\build_importer.py", line 57, in import_build
  File "selenium\webdriver\support\wait.py", line 105, in until
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16
```

**Comment by crafty35a** [comment]
> You are pasting the build guide. That wont work. You have to paste a build, not a guide. E.g. https://maxroll.gg/d4/planner/dqih026y#3

The UI pretty clearly says that build guides can be pasted
![image](https://github.com/aeon0/d4lf/assets/1082003/c944331b-4c0b-4f2d-979d-aa1666abe181)

**Comment by Maximo1491** [comment]
The build guide should work, I'll take another look at this. But all we do under the hood in this case is click on the planner and use that, so if you do have issues, the direct planner link should be used

**Comment by chrisoro** [comment]
Fixed here: https://github.com/aeon0/d4lf/pull/239

**Comment by Bigginz87** [comment]
this was not fixed. I just updated everything to be sure there were no changes. I just attempted to run this moments ago.

```https://maxroll.gg/d4/planner/ailu5022#4

DevTools listening on ws://127.0.0.1:52772/devtools/browser/3068a06b-1461-4fc4-9bbf-812043cfd1e2
[3012:32020:0523/030552.363:ERROR:device_event_log_impl.cc(195)] [03:05:52.363] USB: usb_service_win.cc:105 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
Created TensorFlow Lite XNNPACK delegate for CPU.
Exception in thread Thread-2 (process):
Traceback (most recent call last):
  File "threading.py", line 1073, in _bootstrap_inner
  File "threading.py", line 1010, in run
  File "keyboard\_generic.py", line 58, in process
  File "keyboard\__init__.py", line 218, in pre_process_event
  File "keyboard\__init__.py", line 649, in <lambda>
  File "main.py", line 43, in <lambda>
  File "utils\build_importer.py", line 57, in import_build
  File "selenium\webdriver\support\wait.py", line 105, in until
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
        GetHandleVerifier [0x00007FF6F54B1522+60802]
        (No symbol) [0x00007FF6F542AC22]
        (No symbol) [0x00007FF6F52E7CE4]
        (No symbol) [0x00007FF6F5336D4D]
        (No symbol) [0x00007FF6F5336E1C]
        (No symbol) [0x00007FF6F537CE37]
        (No symbol) [0x00007FF6F535ABBF]
        (No symbol) [0x00007FF6F537A224]
        (No symbol) [0x00007FF6F535A923]
        (No symbol) [0x00007FF6F5328FEC]
        (No symbol) [0x00007FF6F5329C21]
        GetHandleVerifier [0x00007FF6F57B41BD+3217949]
        GetHandleVerifier [0x00007FF6F57F6157+3488183]
        GetHandleVerifier [0x00007FF6F57EF0DF+3459391]
        GetHandleVerifier [0x00007FF6F556B8E6+823622]
        (No symbol) [0x00007FF6F5435FBF]
        (No symbol) [0x00007FF6F5430EE4]
        (No symbol) [0x00007FF6F5431072]
        (No symbol) [0x00007FF6F54218C4]
        BaseThreadInitThunk [0x00007FFF1250257D+29]
        RtlUserThreadStart [0x00007FFF144EAA48+40]```

**Comment by zbee** [comment]
@Bigginz87 #239 (where this is getting fixed) has not been merged yet, watch that PR for updates

**Comment by chrisoro** [comment]
Yes version is not released, yet. You could run it from source to verify
